### ISSUE TITLE
double dlna-devices

### ISSUE THREAD

**Issue by bvdbos** [athombv/org.upnp#2]
Start fresh: delete devices, delete upnp, ptp on Homey and re-install upnp with --run. judging commandline no devices to be deleted, one device found. Add upnp-device gives the same device twice:
![2017-04-15 10_16_24- 558 zones devices - homey](https://cloud.githubusercontent.com/assets/1064079/25062078/048eb84e-21c5-11e7-9e62-8f692f6036cb.png)

**Comment by bvdbos** [comment]
`Hello world!
Found device { deviceType: 'urn:schemas-upnp-org:device:MediaRenderer:1',
  friendlyName: 'Philips NP2900',
  manufacturer: 'Royal Philips Electronics',
  manufacturerURL: 'http://www.philips.com',
  modelName: 'NP',
  modelNumber: '2900',
  modelDescription: 'Philips Streamium HiFi Player',
  UDN: 'uuid:00000081-0000-5000-0000-00903e893012',
  icons: [],
  services: 
   { 'urn:upnp-org:serviceId:RenderingControl': 
      { serviceType: 'urn:schemas-upnp-org:service:RenderingControl:1',
        SCPDURL: 'http://10.0.4.8:8080/RenderCtl.xml',
        controlURL: 'http://10.0.4.8:8080/UD/action?0',
        eventSubURL: 'http://10.0.4.8:8080/sub?0' },
     'urn:upnp-org:serviceId:ConnectionManager': 
      { serviceType: 'urn:schemas-upnp-org:service:ConnectionManager:1',
        SCPDURL: 'http://10.0.4.8:8080/MrConnMgr.xml',
        controlURL: 'http://10.0.4.8:8080/UD/action?1',
        eventSubURL: 'http://10.0.4.8:8080/sub?1' },
     'urn:upnp-org:serviceId:AVTransport': 
      { serviceType: 'urn:schemas-upnp-org:service:AVTransport:1',
        SCPDURL: 'http://10.0.4.8:8080/MrAvTransport.xml',
        controlURL: 'http://10.0.4.8:8080/UD/action?2',
        eventSubURL: 'http://10.0.4.8:8080/sub?2' } } }
[log] capabilities.speaker_playing.get
[log] capabilities.volume_set.get
[log] capabilities.volume_mute.get
[log] added { id: 'uuid:00000081-0000-5000-0000-00903e893012::urn:schemas-upnp-org:device:MediaRenderer:1' }
[log] capabilities.speaker_playing.get
[log] capabilities.volume_set.get
[log] capabilities.volume_mute.get
get volume null 0.02
`

**Comment by bvdbos** [comment]
switching to "music"-tab in Homey does nothing on commandline. Choosing np2900 as player gives double volume-get?

[log] capabilities.volume_set.get
[log] capabilities.volume_set.get
get volume null 0.02
get volume null 0.02
[log] capabilities.volume_set.get
get volume null 0.02

**Comment by bvdbos** [comment]
trying to add a device once more says there are no new devices.

**Comment by caseda** [comment]
I had this issue as well,
but you can only click one of the checkboxes, not both.

If you press the bottom one, you select the top one,
but if you select the top one, it will still select the top device

**Comment by BasKiers** [comment]
I've fixed this issue in the next commit, thanks.
