### ISSUE TITLE
choosing other player shouldn't stop playing current player

### ISSUE THREAD

**Issue by bvdbos** [athombv/org.upnp#7]
Play a track on a dlna-device (through external controller) and go to music in Homey-interface. Choose dlna-player, nothing happens (and current track doesn't show but that's bug #6) and shouldn't happen. Then choose another player like chromecast. Current player stops which it shouldn't. That is, unless you want to create music-follow-me but it should be possible to independently control multiple devices.

**Comment by jeroenvollenbrock** [comment]
This is intended behavior, Homey music can only control 1 music player at a time
