### ISSUE TITLE
force re-scan of devices

### ISSUE THREAD

**Issue by bvdbos** [athombv/org.upnp#8]
I think Homey is supposed to automatically rescans for network-devices once every 5 minutes (https://github.com/athombv/org.upnp/blob/master/node_modules/upnp-device-client/index.js#L15) but this doesn't always seem to work (still trying to replicate). But, to be able to control our devices, it would be good to have an action-card to force a rescan after a device is turned on.

**Comment by BasKiers** [comment]
Rescan should happen every 10 minutes. I've set it to 2 minutes in the next commit.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!

**Comment by bvdbos** [comment]
@jeroenvollenbrock This issue still exists. When I power on my stereo i don't want to have to wait xxx minutes before Homey broadcasts an upnp discovery message. We can choose not to allow this but it's not fixed ;-)
